// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DeltaHedgePnL
NumericVector DeltaHedgePnL(int nInt, double strike, double spot, double vol_real, double r, double expiry, double vol_implied, double nSims);
RcppExport SEXP Hedging_DeltaHedgePnL(SEXP nIntSEXP, SEXP strikeSEXP, SEXP spotSEXP, SEXP vol_realSEXP, SEXP rSEXP, SEXP expirySEXP, SEXP vol_impliedSEXP, SEXP nSimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nInt(nIntSEXP);
    Rcpp::traits::input_parameter< double >::type strike(strikeSEXP);
    Rcpp::traits::input_parameter< double >::type spot(spotSEXP);
    Rcpp::traits::input_parameter< double >::type vol_real(vol_realSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type expiry(expirySEXP);
    Rcpp::traits::input_parameter< double >::type vol_implied(vol_impliedSEXP);
    Rcpp::traits::input_parameter< double >::type nSims(nSimsSEXP);
    rcpp_result_gen = Rcpp::wrap(DeltaHedgePnL(nInt, strike, spot, vol_real, r, expiry, vol_implied, nSims));
    return rcpp_result_gen;
END_RCPP
}
// DeltaGammaHedgePnL
NumericVector DeltaGammaHedgePnL(int nInt, double strike1, double strike2, double spot, double vol_real, double r, double expiry, double vol_implied, double nSims);
RcppExport SEXP Hedging_DeltaGammaHedgePnL(SEXP nIntSEXP, SEXP strike1SEXP, SEXP strike2SEXP, SEXP spotSEXP, SEXP vol_realSEXP, SEXP rSEXP, SEXP expirySEXP, SEXP vol_impliedSEXP, SEXP nSimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nInt(nIntSEXP);
    Rcpp::traits::input_parameter< double >::type strike1(strike1SEXP);
    Rcpp::traits::input_parameter< double >::type strike2(strike2SEXP);
    Rcpp::traits::input_parameter< double >::type spot(spotSEXP);
    Rcpp::traits::input_parameter< double >::type vol_real(vol_realSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type expiry(expirySEXP);
    Rcpp::traits::input_parameter< double >::type vol_implied(vol_impliedSEXP);
    Rcpp::traits::input_parameter< double >::type nSims(nSimsSEXP);
    rcpp_result_gen = Rcpp::wrap(DeltaGammaHedgePnL(nInt, strike1, strike2, spot, vol_real, r, expiry, vol_implied, nSims));
    return rcpp_result_gen;
END_RCPP
}
